title: A Winsome Life
author: Melvin Lee
email: melvinlee@awinsomelife.org
description: > # this means to ignore newlines until "baseurl:"
  Full Stack Developer Trainee, Digital Marketer, Tech Geek.

# social links
twitter_username: awinsomelife # DO NOT include the @ character, or else the build will fail!
github_username:  awinsomelife # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
